version: '3.8'
services:
  web:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      LABBEAUTY_DB_DSN: ${LABBEAUTY_DB_DSN}
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5